#!/bin/bash

echo Update environment files...
cp ./thefoot/.env ../private/apps/TheFootChat/
cp ./thefoot/meili.env ../private/apps/TheFootChat/

echo Updating LibreChat config file...
cp ./thefoot/librechat.yaml ../private/apps/TheFootChat/
